### ISSUE TITLE
Wrong Recipe results?

### ISSUE THREAD

**Issue by flautines** [keckrich/DST-Crock-Pot-Calculator#1]
1 Monster Meat
1 Egg
1 Morsel
1 Twig
---------------
The calculator gives as a result Bacon and Eggs but in the game I got Kabobs.

I should mention that my eggs were a bit spoiled (orange) if that's the reason for the result.

**Comment by keckrich** [comment]
Thanks for pointing that out. This issue is now fixed. The actual recipe requires 2 eggs or one large egg
